blank_issues_enabled: false
contact_links:
  - name: STATUS.UIC.EDU
    url: https://status.uic.edu
    about: Check status for all online UIC systems
  - name: RED DEVELOPER DOCUMENTATION
    url: https://develop.red.uic.edu/
    about: Codebase documentation for web developers
  - name: UIC RED WORDPRESS MULTISITE SERVICE
    url: https://red.uic.edu/
    about: General information about the Wordpress Multisite service, documentation and support for site administrators