blank_issues_enabled: false
contact_links:
  - name: Red developer documentation
    url: https://develop.red.uic.edu/
    about: Codebase documentation for web developers
  - name: Red Multsite service
    url: https://red.uic.edu/
    about: General information about the Wordpress Multisite service, User & administrative support