name: Feature Request
description: Propose a feature request or enhancement
title: "[Feature Request]: "
labels: ["feature-request","enhancement"]
assignees:
  - none
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your submission.
  - type: textarea
    id: feature-request-name
    attributes:
      label: Feature request name
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex netid@uic.edu
    validations:
      required: false
  - type: checkboxes
    id: dev-status
    attributes:
      label: "Can you contribute to the codebase for this feature?"
      options:
        - label: Testing 1 2 3 
          required: true
  - type: textarea
    id: campus-unit
    attributes:
      label: Campus Unit
      description: Please enter your VC unit or College if applicable
    validations:
      required: true
  - type: checkboxes
    id: use-cases
    attributes:
      label: What best fits your motivations for this request? Check all that apply.
      description: descript
      options:
        - label: Better marketing and/or branding
          required: false
        - label: Assists with recruitment
          required: false
        - label: Improves experience for a site visitor
          required: false
        - label: Improves experience for a WordPress user (site admin, editor, etc)
          required: false
        - label: Needed for data collection
          required: false
  - type: textarea
    id: propose-solution
    attributes:
      label: Propose a solution
    validations:
      required: true
  - type: textarea
    id: who-will-use
    attributes:
      label: Who will use this feature?
    validations:
      required: true
  - type: textarea
    id: who-will-benefit
    attributes:
      label: Who will benefit from this feature?
    validations:
      required: true
  - type: textarea
    id: is-feature-necessary
    attributes:
      label: Is this feature necessary for a particular Red site to function?
    validations:
      required: true
  - type: checkboxes
    id: request-may-involve
    attributes:
      label: This request may involve
      options:
        - label: Component
          required: false
        - label: Custom Post type
          required: false
        - label: Plugin
          required: false
        - label: Acquisition of a paid license
          required: false
        - label: Other/I don't know
          required: false
  - type: textarea
    id: who-will-use
    attributes:
      label: Please provide links to similar solutions found on other sites (if applicable)
    validations:
      required: false
