name: Bug report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]


body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Thank you for your submission

  - type: input
    id: contact-name
    attributes:
      label: Your name
      placeholder: "Your name"
    validations:
      required: true
  - type: input
    id: contact-email
    attributes:
      label: Your email
      placeholder: "netid@uic.edu"
    validations:
      required: true
  - type: input
    id: vc-unit
    attributes:
      label: VC Unit/College and your department name
      placeholder: "Vice Chancellor for Innovation, Office of Intergalactic Outreach"
    validations:
      required: true

  - type: dropdown
    id: dev-status
    attributes:
      label: "Can you contribute to the codebase for this bug/issue?"
      multiple: false
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: checkboxes
    id: issue-list
    attributes:
      label: Issue
      options:
        - label: I can't log in
          required: false
        - label: A page is not displaying correctly
          required: false
        - label: Menu problems
          required: false
        - label: Form problems
          required: false
        - label: Other
          required: false

  - type: dropdown
    id: error-message
    attributes:
      label: Do you see an error message?
      multiple: false
      options:
        - "No"
        - "Yes"
    validations:
      required: false

  - type: textarea
    id: describe-problem
    attributes:
      label: "Describe the problem"
    validations:
      required: true