name: Feature Request
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your submission
  - type: textarea
    id: request-name
    attributes:
      label: Name of this request
      placeholder: "example: Component for squirrel profiles"
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. netid@uic.edu
    validations:
      required: true
  - type: dropdown
    id: dev-status
    attributes:
      label: "Can you contribute to the codebase for this feature?"
      options:
        - "No"
        - "Yes"
  - type: textarea
    id: vc-unit
    attributes:
      label: Campus unit
      description: "Please enter your VC unit or College if applicable"
    validations:
      required: true
  - type: textarea
    id: propose-solution
    attributes:
      label: "Propose a solution"
    validations:
      required: true
  - type: textarea
    id: who-will-use
    attributes:
      label: "Who will use this feature?"
    validations:
      required: true
  - type: textarea
    id: who-will-benefit
    attributes:
      label: "Who benefit from this feature?"
    validations:
      required: true
  - type: textarea
    id: is-feature-necessary
    attributes:
      label: "Is this feature necessary for a particular Red site to function?"
    validations:
      required: true
  - type: textarea
    id: provide-links-solutions
    attributes:
      label: "Please provide links to similar solutions found on other sites (if applicable)"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "This request may involve"
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: Component
          required: false
        - label: Custom Post type
          required: false
        - label: Plugin
          required: false
        - label: Acquisition of a paid license
          required: false
        - label: Other/I don't know
          required: false