name: Feature Request
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your submission
  - type: textarea
    id: request-name
    attributes:
      label: Name of this request
      placeholder: "example: Component for squirrel profiles"
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. netid@uic.edu
    validations:
      required: true
  - type: dropdown
    id: dev-status
    attributes:
      label: "Can you contribute to the codebase for this feature?"
      multiple: false
      options:
        - No
        - Yes
  - type: textarea
    id: vc-unit
    attributes:
      label: Campus unit
      description: "Please enter your VC unit or College if applicable"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

