name: Accessibility Checker

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: '${{ secrets.A11Y_LINTER_TOKEN }}'
  PREVIEW_URL: ${{ env.PREVIEW_URL }}

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
          node node_modules/puppeteer/install.js
      - name: Run pa11y-ci
        env:
          PREVIEW_URL: ${{ env.PREVIEW_URL }}
        run: npx pa11y-ci --config=.pa11yci.json --json "${{ env.PREVIEW_URL }}" > results.json
      - name: List files in directory
        run: ls -al
      - name: Set file permissions
        run: chmod 666 results.json
      - name: Check if results.json exists and is not empty
        run: |
          if [ -s "results.json" ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "$(cat results.json)"
          else
            echo "Error: results.json is empty or does not exist. Also, this should be the PR number: ${{ github.event.pull_request.number }}."
          fi
      - name: List files in directory
        run: ls -al
