name: Accessibility Checker

on:
  pull_request:
    types: [opened, synchronize]

env:
  GITHUB_TOKEN: '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'

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
          node node_modules/puppeteer/install.js
      - name: Run pa11y-ci
        run: npx pa11y-ci --config=.pa11yci.json --json > results.json && gh pr comment ${{ github.event.pull_request.number }} --body "$(cat results.json)"
