name: Accessibility Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install axe-core
      - name: Make axe executable
        run: chmod +x node_modules/axe-core/bin/axe
      - name: Run Axe-core
        run: node node_modules/axe-core/axe.js ${{ github.event.pull_request.head.ref }}
