name: Accessibility Checker

on:
  pull_request:

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run pa11y
        run: npx pa11y-ci --config=.pa11yci.json --json > results.json
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: accessibility-results
          path: results.json
