name: 'Deployment status test'

on:
  push:
    branches: [ develop ]

env:
  color_var: 0be642

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📣 Send teams notification
        uses: simbo/msteams-message-card-action@latest
        with:
          webhook: https://uic365.webhook.office.com/webhookb2/e2758c1c-477f-4de7-b1bd-c8f35fe1d105@e202cd47-7a56-4baa-99e3-e3b71a7c77dd/IncomingWebhook/ef5cd950674649228b1ae1c203a82a2a/68f631fe-fabd-412d-b045-29ece196782a
          color: ${{ env.color_var }}
          title: ${{ github.workflow }}
          message: ${{ github.repository }}<hr style="height:1px;color:#${{ env.color_var }};background-color:#${{ env.color_var }};">
          buttons: |
            View Build https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}
            View Project https://github.com/orgs/uic-ts/projects/1
          sections: |
            -
              activityTitle:
              activitySubtitle:
              facts:
                -
                  name: "job status:"
                  value: ${{ job.status }}


                -
                  name: "github event name"
                  value: ${{ github.event_name }}

                -
                  name: "triggered by"
                  value: ${{ github.triggering_actor }}
