name: This is the workflow name

on:
  pull_request:
    branches: [ develop ]
  issues:
    types: [ opened ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📣 Send teams notification
        uses: simbo/msteams-message-card-action@latest
        with:
          webhook: https://uic365.webhook.office.com/webhookb2/e2758c1c-477f-4de7-b1bd-c8f35fe1d105@e202cd47-7a56-4baa-99e3-e3b71a7c77dd/IncomingWebhook/ef5cd950674649228b1ae1c203a82a2a/68f631fe-fabd-412d-b045-29ece196782a
          title: ${{ github.event.pull_request.title }}
          message: message
          color: ff69b4
          buttons: |
            'Button 1' https://uic.edu/
            'Button number two' https://red.uic.edu/
          sections: |
            -
              activityTitle: activityTitle
              activitySubtitle: activitySubtitle, timestamp?
              facts:
                -
                  name: "github.event_name"
                  value: ${{ github.event_name }}
                -
                  name: "github.workflow"
                  value: ${{ github.workflow }}
                -
                  name: "github.run_id"
                  value: ${{ github.run_id }}
                -
                  name: "github.ref"
                  value: ${{ github.ref }}
                -
                  name: "github.ref_name"
                  value: ${{ github.ref_name }}
                -
                  name: "github.action_status"
                  value: ${{ github.action_status }}
                -
                  name: "github.actor"
                  value: ${{ github.actor }}
                -
                  name: "github.action"
                  value: ${{ github.action }}
                -
                  name: "github.env"
                  value: ${{ github.env}}
                -
                  name: "github.event"
                  value: ${{ github.event }}
                -
                  name: "github.event"
                  value: ${{ github.event_name }}
                -
                  name: "github.job"
                  value: ${{ github.job }}
                -
                  name: "github.job_workflow_sha"
                  value: ${{ github.job_workflow_sha }}
                -
                  name: "github.repository"
                  value: ${{ github.repository }}
                -
                  name: "github.triggering_actor"
                  value: ${{ github.triggering_actor }}


              text: Lorem ipsum 