name: 'Pull Request'

on:
  pull_request:
    branches: [ develop ]
  issues:
    types: [ opened ]
env:
  develop_branch: 'Develop'
  from_var: 'from'
  submitted_by: 'submitted by'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📣 Send teams notification
        uses: simbo/msteams-message-card-action@latest
        with:
          webhook: https://uic365.webhook.office.com/webhookb2/e2758c1c-477f-4de7-b1bd-c8f35fe1d105@e202cd47-7a56-4baa-99e3-e3b71a7c77dd/IncomingWebhook/ef5cd950674649228b1ae1c203a82a2a/68f631fe-fabd-412d-b045-29ece196782a
          title: ${{ github.workflow }}${{ env.develop_branch }}
          message: ${{ env.from_var }} ${{ github.event.pull_request.title }}
          color: ff69b4
          buttons: |
            'Button 1' https://uic.edu/
            'Button number two' https://red.uic.edu/
          sections: |
            -
              activityTitle: ${{ env.submitted_by }} ${{ github.triggering_actor }}
              activitySubtitle: activitySubtitle
              facts:
                -
                  name: "github.event"
                  value: ${{ github.event }}
                -
                  name: "github.event_name"
                  value: ${{ github.event_name }}
                -
                  name: "github.job"
                  value: ${{ github.job }}
                -
                  name: "github.job_workflow_sha"
                  value: ${{ github.job_workflow_sha }}
                -
                  name: "github.repository"
                  value: ${{ github.repository }}



              text: Lorem ipsum 