name: build
on:
  pull_request:
    branches:
      - develop
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          exit 0
  build:
    name: Checkout and notify
    needs: [ TestJob ]
    if: ${{always()}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - uses: freezer00/teams-webhook-action@v1.0.0
        with:
          title: Pull request
          webhook_url: ${{secrets.webhook}}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          additional_button_title: |-
            Link to Google
            Link to Microsoft
          additional_button_url: |-
            https://google.com
            https://www.microsoft.com/de-de/microsoft-teams
          dry_run: false